# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. 

fastlane_version "1.39.0"

default_platform :ios

lane :prod do
 ensure_git_status_clean
 increment_build_number(
    xcodeproj: "Client.xcodeproj"
  )
  build_app(scheme: "Karma", xcargs: "-allowProvisioningUpdates", export_options: {
    provisioningProfiles: { 
      "com.mykarma.karmasearch" => "Karma Search AppStore",
      "com.mykarma.karmasearch.CredentialProvider" => "CredentialProvider AppStore",
	"com.mykarma.karmasearch.NotificationService" => "NotificationService AppStore",
	"com.mykarma.karmasearch.ShareTo" => "ShareTo AppStore",
	"com.mykarma.karmasearch.WidgetKit" => "Widget AppStore"
    }
})
upload_to_testflight
commit_version_bump(xcodeproj: "Client.xcodeproj")
push_to_git_remote
end
