# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/. 

fastlane_version "1.39.0"

default_platform :ios

lane :prod do
 increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "Client.xcodeproj"
  )
  build_app(scheme: "Karma", xcargs: "-allowProvisioningUpdates")
upload_to_testflight
end
